// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote470Plus.Infrastructure.Persistence.Contexts;

#nullable disable

namespace eVote470Plus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EVote470PlusContext))]
    [Migration("20260427014849_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.People.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.People.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CitizenId"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("CitizenId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.ToTable("Citizens", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.People.PoliticalLeader", b =>
                {
                    b.Property<string>("PoliticalLeaderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.HasKey("PoliticalLeaderId");

                    b.HasIndex("PoliticalPartyId")
                        .IsUnique();

                    b.ToTable("PoliticalLeaders", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.CandidatePosition", b =>
                {
                    b.Property<int>("CandidatePositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidatePositionId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPositionId")
                        .HasColumnType("int");

                    b.HasKey("CandidatePositionId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("PoliticalPositionId");

                    b.ToTable("CandidatePositions", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.Election", b =>
                {
                    b.Property<int>("ElectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ElectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ElectionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("ElectionId");

                    b.ToTable("Elections", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.ElectionPosition", b =>
                {
                    b.Property<int>("ElectionPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ElectionPositionId"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPositionId")
                        .HasColumnType("int");

                    b.HasKey("ElectionPositionId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PoliticalPositionId");

                    b.ToTable("ElectionPositions", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.PoliticalParty", b =>
                {
                    b.Property<int>("PoliticalPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PoliticalPartyId"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("PoliticalPartyId");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.ToTable("PoliticalParties", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.PoliticalPosition", b =>
                {
                    b.Property<int>("PoliticalPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PoliticalPositionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("PoliticalPositionId");

                    b.ToTable("PoliticalPositions", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Relations.PoliticalAlliance", b =>
                {
                    b.Property<int>("PoliticalAllianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PoliticalAllianceId"));

                    b.Property<int>("ReceiverPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SenderPartyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PoliticalAllianceId");

                    b.HasIndex("ReceiverPartyId");

                    b.HasIndex("SenderPartyId");

                    b.ToTable("PoliticalAlliances", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Relations.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VoteId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 4, 27, 1, 48, 48, 708, DateTimeKind.Utc).AddTicks(2143));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPositionId")
                        .HasColumnType("int");

                    b.HasKey("VoteId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PoliticalPositionId");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.People.Candidate", b =>
                {
                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalParty", "PoliticalParty")
                        .WithMany("Candidates")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.People.PoliticalLeader", b =>
                {
                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalParty", "PoliticalParty")
                        .WithOne("PoliticalLeader")
                        .HasForeignKey("eVote470Plus.Core.Domain.Entities.People.PoliticalLeader", "PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.CandidatePosition", b =>
                {
                    b.HasOne("eVote470Plus.Core.Domain.Entities.People.Candidate", "Candidate")
                        .WithMany("CandidatePositions")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalPosition", "PoliticalPosition")
                        .WithMany()
                        .HasForeignKey("PoliticalPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("PoliticalParty");

                    b.Navigation("PoliticalPosition");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.ElectionPosition", b =>
                {
                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.Election", "Election")
                        .WithMany("ElectionPositions")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalPosition", "PoliticalPosition")
                        .WithMany()
                        .HasForeignKey("PoliticalPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("PoliticalPosition");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Relations.PoliticalAlliance", b =>
                {
                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalParty", "ReceiverParty")
                        .WithMany("ReceivedAlliances")
                        .HasForeignKey("ReceiverPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalParty", "SenderParty")
                        .WithMany("SentAlliances")
                        .HasForeignKey("SenderPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverParty");

                    b.Navigation("SenderParty");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Relations.Vote", b =>
                {
                    b.HasOne("eVote470Plus.Core.Domain.Entities.People.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote470Plus.Core.Domain.Entities.People.Citizen", "Citizen")
                        .WithMany("Votes")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.Election", "Election")
                        .WithMany("Votes")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote470Plus.Core.Domain.Entities.Political.PoliticalPosition", "PoliticalPosition")
                        .WithMany()
                        .HasForeignKey("PoliticalPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Citizen");

                    b.Navigation("Election");

                    b.Navigation("PoliticalPosition");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.People.Candidate", b =>
                {
                    b.Navigation("CandidatePositions");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.People.Citizen", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.Election", b =>
                {
                    b.Navigation("ElectionPositions");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote470Plus.Core.Domain.Entities.Political.PoliticalParty", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("PoliticalLeader");

                    b.Navigation("ReceivedAlliances");

                    b.Navigation("SentAlliances");
                });
#pragma warning restore 612, 618
        }
    }
}
